export const ADD_BLUEPRINT_NODE = 'ADD_BLUEPRINT_NODE';
export const UPDATE_BLUEPRINT_NODE = 'UPDATE_BLUEPRINT_NODE';
export const ADD_FETCHED_BLUEPRINTS_DATA = 'ADD_FETCHED_BLUEPRINTS_DATA';
export const FETCH_BLUEPRINTS_CATEGORY = 'FETCH_BLUEPRINTS_CATEGORY';